import db, { initDB } from './database.js'

initDB()

const EXERCISES = [
  // CHEST
  { name: 'Barbell Bench Press', muscle_group: 'Chest', secondary_muscles: 'Triceps,Front Deltoid', equipment: 'Barbell,Bench', instructions: 'Lie flat on bench. Grip bar slightly wider than shoulder-width. Lower bar to mid-chest under control. Press back up to full arm extension. Keep feet flat on floor and back naturally arched.' },
  { name: 'Incline Barbell Press', muscle_group: 'Chest', secondary_muscles: 'Triceps,Front Deltoid', equipment: 'Barbell,Incline Bench', instructions: 'Set bench to 30-45 degrees. Grip bar slightly wider than shoulder-width. Lower bar to upper chest. Press upward and slightly back. Targets upper chest.' },
  { name: 'Decline Barbell Press', muscle_group: 'Chest', secondary_muscles: 'Triceps', equipment: 'Barbell,Decline Bench', instructions: 'Set bench to -15 to -30 degrees. Feet secured under pads. Lower bar to lower chest. Press straight up. Emphasizes lower chest fibers.' },
  { name: 'Dumbbell Bench Press', muscle_group: 'Chest', secondary_muscles: 'Triceps,Front Deltoid', equipment: 'Dumbbells,Bench', instructions: 'Hold dumbbells at chest level, palms forward. Press up until arms extended, slight inward arc. Lower slowly. Greater range of motion than barbell.' },
  { name: 'Incline Dumbbell Press', muscle_group: 'Chest', secondary_muscles: 'Triceps,Front Deltoid', equipment: 'Dumbbells,Incline Bench', instructions: 'Set bench to 30-45 degrees. Press dumbbells from shoulder height to arms extended above upper chest. Great upper chest builder.' },
  { name: 'Dumbbell Flyes', muscle_group: 'Chest', secondary_muscles: 'Front Deltoid', equipment: 'Dumbbells,Bench', instructions: 'Lie on bench with dumbbells above chest, slight elbow bend. Open arms in wide arc until stretch felt in chest. Reverse the arc to return. Maintain soft elbow throughout.' },
  { name: 'Cable Crossover', muscle_group: 'Chest', secondary_muscles: 'Front Deltoid', equipment: 'Cable Machine', instructions: 'Stand between high cable pulleys. Pull cables down and across body in sweeping arc. Squeeze pecs at bottom. Control the return. Excellent for chest isolation.' },
  { name: 'Push-Up', muscle_group: 'Chest', secondary_muscles: 'Triceps,Core,Front Deltoid', equipment: 'Bodyweight', instructions: 'Start in high plank, hands slightly wider than shoulders. Lower chest to floor keeping body straight. Push back up. Can be modified (knees) or progressed (elevated feet).' },
  { name: 'Dips (Chest Version)', muscle_group: 'Chest', secondary_muscles: 'Triceps,Front Deltoid', equipment: 'Dip Bars', instructions: 'Grip parallel bars, lean torso forward 30 degrees. Lower body until upper arms are parallel to floor. Push back up. Forward lean shifts emphasis to chest over triceps.' },
  { name: 'Pec Deck Machine', muscle_group: 'Chest', secondary_muscles: 'Front Deltoid', equipment: 'Machine', instructions: 'Sit with arms at 90-degree angle against pads. Bring arms together in front of chest. Hold squeeze 1 second. Release slowly. Excellent isolation exercise.' },

  // BACK
  { name: 'Barbell Deadlift', muscle_group: 'Back', secondary_muscles: 'Glutes,Hamstrings,Core,Traps', equipment: 'Barbell', instructions: 'Stand with bar over mid-foot. Hinge at hips, grip just outside legs. Brace core, drive through floor. Keep bar close to body. Lock out hips and knees simultaneously. Lower with control.' },
  { name: 'Pull-Up', muscle_group: 'Back', secondary_muscles: 'Biceps,Rear Deltoid', equipment: 'Pull-Up Bar', instructions: 'Hang from bar with overhand grip, shoulder-width or wider. Pull body up until chin clears bar. Lower fully. Keep elbows pointed down and outward.' },
  { name: 'Chin-Up', muscle_group: 'Back', secondary_muscles: 'Biceps', equipment: 'Pull-Up Bar', instructions: 'Hang from bar with underhand (supinated) grip at shoulder-width. Pull until chin above bar. Underhand grip increases bicep involvement compared to pull-up.' },
  { name: 'Barbell Bent-Over Row', muscle_group: 'Back', secondary_muscles: 'Biceps,Rear Deltoid,Core', equipment: 'Barbell', instructions: 'Hinge forward to roughly 45 degrees, back flat. Pull bar to lower ribcage. Squeeze shoulder blades together at top. Lower with control.' },
  { name: 'Seated Cable Row', muscle_group: 'Back', secondary_muscles: 'Biceps,Rear Deltoid', equipment: 'Cable Machine', instructions: 'Sit with slight forward lean. Pull handle to lower ribcage. Drive elbows back and squeeze shoulder blades. Return slowly. Keep lower back stable.' },
  { name: 'Lat Pulldown', muscle_group: 'Back', secondary_muscles: 'Biceps,Rear Deltoid', equipment: 'Cable Machine', instructions: 'Grip bar wider than shoulder-width. Pull bar to upper chest while leaning slightly back. Elbows drive down and back. Control the return.' },
  { name: 'T-Bar Row', muscle_group: 'Back', secondary_muscles: 'Biceps,Rear Deltoid', equipment: 'T-Bar Machine', instructions: 'Straddle bar, hinge forward. Pull bar to chest. Squeeze back at top. Allows heavier loads than dumbbell row.' },
  { name: 'Single-Arm Dumbbell Row', muscle_group: 'Back', secondary_muscles: 'Biceps,Rear Deltoid', equipment: 'Dumbbell,Bench', instructions: 'Place one knee and hand on bench. Row dumbbell to hip, elbow close to body. Lower fully. Allows great range of motion.' },
  { name: 'Face Pull', muscle_group: 'Back', secondary_muscles: 'Rear Deltoid,Traps,Rotator Cuff', equipment: 'Cable Machine,Rope', instructions: 'Set cable at eye height with rope attachment. Pull rope to forehead, elbows flared high. External rotate at end. Essential for shoulder health.' },
  { name: 'Romanian Deadlift', muscle_group: 'Back', secondary_muscles: 'Hamstrings,Glutes', equipment: 'Barbell', instructions: 'Start standing, push hips back while lowering bar along legs. Keep back flat and slight knee bend. Lower until hamstring stretch. Drive hips forward to return.' },

  // SHOULDERS
  { name: 'Overhead Press (Barbell)', muscle_group: 'Shoulders', secondary_muscles: 'Triceps,Traps,Core', equipment: 'Barbell', instructions: 'Stand with barbell at collar bone, grip just outside shoulders. Press directly overhead to full arm extension. Lower to clavicle. Maintain tight core throughout.' },
  { name: 'Dumbbell Shoulder Press', muscle_group: 'Shoulders', secondary_muscles: 'Triceps,Traps', equipment: 'Dumbbells', instructions: 'Sit or stand holding dumbbells at ear height, palms forward. Press overhead until arms extended. Lower to start.' },
  { name: 'Lateral Raise', muscle_group: 'Shoulders', secondary_muscles: 'Traps', equipment: 'Dumbbells', instructions: 'Stand with dumbbells at sides, slight elbow bend. Raise arms to shoulder height, palms down. Lower slowly over 2-3 seconds.' },
  { name: 'Front Raise', muscle_group: 'Shoulders', secondary_muscles: 'Chest', equipment: 'Dumbbells,Barbell', instructions: 'Hold weight in front of thighs. Raise arms straight to shoulder height. Lower slowly. Targets anterior deltoid.' },
  { name: 'Arnold Press', muscle_group: 'Shoulders', secondary_muscles: 'Triceps,Traps', equipment: 'Dumbbells', instructions: 'Start with dumbbells at chin height, palms facing you. As you press up, rotate palms outward. Finish with palms forward at top. Reverse on way down.' },
  { name: 'Rear Delt Fly', muscle_group: 'Shoulders', secondary_muscles: 'Traps', equipment: 'Dumbbells,Cable', instructions: 'Bend forward 45-90 degrees. Raise arms out to sides in reverse fly motion. Pinch shoulder blades at top. Targets posterior deltoid.' },
  { name: 'Upright Row', muscle_group: 'Shoulders', secondary_muscles: 'Traps,Biceps', equipment: 'Barbell,Dumbbells', instructions: 'Hold bar with overhand narrow grip. Pull bar straight up to chin level, elbows high and wide. Lower slowly.' },
  { name: 'Cable Lateral Raise', muscle_group: 'Shoulders', secondary_muscles: 'Traps', equipment: 'Cable Machine', instructions: 'Stand beside cable set at lowest position. Grab cable. Raise arm to side to shoulder height. Constant tension is the advantage over dumbbells.' },

  // LEGS
  { name: 'Barbell Back Squat', muscle_group: 'Legs', secondary_muscles: 'Glutes,Lower Back,Core', equipment: 'Barbell,Squat Rack', instructions: 'Bar on upper traps, feet shoulder-width with toes slightly out. Sit back and down keeping chest tall. Break parallel if mobility allows. Drive through heels to return.' },
  { name: 'Front Squat', muscle_group: 'Legs', secondary_muscles: 'Glutes,Core', equipment: 'Barbell,Squat Rack', instructions: 'Bar resting on front deltoids, elbows high. Sit down keeping torso upright. More quad-dominant and core-demanding than back squat.' },
  { name: 'Leg Press', muscle_group: 'Legs', secondary_muscles: 'Glutes', equipment: 'Machine', instructions: 'Sit in machine with feet shoulder-width on platform. Lower weight until 90-degree knee angle. Press back to near lockout.' },
  { name: 'Bulgarian Split Squat', muscle_group: 'Legs', secondary_muscles: 'Glutes,Core', equipment: 'Dumbbells,Bench', instructions: 'Rear foot elevated on bench, front foot ahead. Lower back knee toward floor. Front shin stays relatively vertical. Excellent for quad development.' },
  { name: 'Leg Curl (Lying)', muscle_group: 'Legs', secondary_muscles: 'Calves', equipment: 'Machine', instructions: 'Lie face down, pad just above ankles. Curl heels toward glutes. Pause at top. Lower slowly. Isolates hamstrings effectively.' },
  { name: 'Leg Extension', muscle_group: 'Legs', secondary_muscles: '', equipment: 'Machine', instructions: 'Sit with pad just above feet. Extend legs to full lockout. Pause to squeeze quad. Lower slowly over 3 seconds. Pure quad isolation.' },
  { name: 'Hack Squat', muscle_group: 'Legs', secondary_muscles: 'Glutes', equipment: 'Machine', instructions: 'Stand on platform with back against pad, feet shoulder-width. Lower until thighs parallel or below. Press back up.' },
  { name: 'Standing Calf Raise', muscle_group: 'Legs', secondary_muscles: '', equipment: 'Machine,Smith Machine', instructions: 'Stand on edge with balls of feet, heels hanging. Lower heels below platform. Rise as high as possible on toes. Hold 1 second at top.' },
  { name: 'Seated Calf Raise', muscle_group: 'Legs', secondary_muscles: '', equipment: 'Machine', instructions: 'Sit with pads on lower thighs, balls of feet on platform. Raise and lower heels. Targets soleus due to bent knee position.' },
  { name: 'Walking Lunge', muscle_group: 'Legs', secondary_muscles: 'Glutes,Core', equipment: 'Bodyweight,Dumbbells', instructions: 'Step forward into lunge, lower back knee toward floor. Drive front foot to step forward into next lunge. Alternate legs.' },
  { name: 'Goblet Squat', muscle_group: 'Legs', secondary_muscles: 'Glutes,Core', equipment: 'Dumbbell,Kettlebell', instructions: 'Hold weight at chest with both hands. Squat down keeping chest tall and elbows inside knees. Excellent teaching tool for squat mechanics.' },
  { name: 'Sumo Squat', muscle_group: 'Legs', secondary_muscles: 'Glutes,Adductors', equipment: 'Barbell,Dumbbell,Kettlebell', instructions: 'Wide stance with toes pointed out. Squat down keeping chest tall. More adductor and glute activation than standard squat.' },
  { name: 'Step-Up', muscle_group: 'Legs', secondary_muscles: 'Glutes,Core', equipment: 'Box,Dumbbells', instructions: 'Step onto a box with one foot, drive up to standing. Step down and alternate. Great for unilateral leg strength and balance.' },

  // BICEPS
  { name: 'Barbell Curl', muscle_group: 'Biceps', secondary_muscles: 'Forearms', equipment: 'Barbell', instructions: 'Stand with barbell at thighs, underhand grip. Curl to shoulder height keeping elbows at sides. Squeeze at top. Lower fully.' },
  { name: 'Dumbbell Alternating Curl', muscle_group: 'Biceps', secondary_muscles: 'Forearms', equipment: 'Dumbbells', instructions: 'Stand or sit with dumbbells at sides. Curl one arm supinating wrist as you lift. Lower and alternate. Supination maximally activates biceps.' },
  { name: 'Hammer Curl', muscle_group: 'Biceps', secondary_muscles: 'Brachialis,Forearms', equipment: 'Dumbbells', instructions: 'Hold dumbbells with neutral grip (palms facing in). Curl to shoulder height without rotating wrist. Targets brachialis and brachioradialis.' },
  { name: 'Preacher Curl', muscle_group: 'Biceps', secondary_muscles: 'Forearms', equipment: 'EZ Bar,Preacher Bench', instructions: 'Rest upper arm on preacher bench pad. Curl bar to chin. Lower fully — full extension stretch is key. Eliminates body swing.' },
  { name: 'Incline Dumbbell Curl', muscle_group: 'Biceps', secondary_muscles: 'Forearms', equipment: 'Dumbbells,Incline Bench', instructions: 'Lie back on incline bench with arms hanging straight. Curl dumbbells. The incline creates greater stretch at bottom.' },
  { name: 'Cable Curl', muscle_group: 'Biceps', secondary_muscles: 'Forearms', equipment: 'Cable Machine', instructions: 'Stand facing low cable, underhand grip on bar or rope. Curl to chin. Cable provides constant tension throughout the range of motion.' },
  { name: 'Concentration Curl', muscle_group: 'Biceps', secondary_muscles: 'Forearms', equipment: 'Dumbbell', instructions: 'Sit on bench, elbow resting on inner thigh. Curl dumbbell to shoulder. Excellent isolation exercise, reduces ability to cheat with body swing.' },

  // TRICEPS
  { name: 'Close-Grip Bench Press', muscle_group: 'Triceps', secondary_muscles: 'Chest,Front Deltoid', equipment: 'Barbell,Bench', instructions: 'Same as bench press but hands 6-8 inches apart. Lower bar to lower chest/sternum. Elbows stay closer to body. Compounds tricep strength.' },
  { name: 'Tricep Pushdown', muscle_group: 'Triceps', secondary_muscles: '', equipment: 'Cable Machine', instructions: 'Stand at high cable, overhand grip on bar or rope. Push down to full arm extension. Keep elbows at sides. Control return.' },
  { name: 'Overhead Tricep Extension', muscle_group: 'Triceps', secondary_muscles: '', equipment: 'Dumbbell,EZ Bar,Cable', instructions: 'Hold weight overhead with arms extended. Lower behind head by bending at elbows. Press back to full extension. Overhead position provides maximum stretch.' },
  { name: 'Skull Crusher', muscle_group: 'Triceps', secondary_muscles: '', equipment: 'EZ Bar,Barbell,Bench', instructions: 'Lie on bench, EZ bar above chest. Lower bar toward forehead by bending elbows. Press back up. Keep upper arms perpendicular to floor throughout.' },
  { name: 'Dips (Triceps Version)', muscle_group: 'Triceps', secondary_muscles: 'Chest,Front Deltoid', equipment: 'Dip Bars', instructions: 'Grip parallel bars, keep torso upright (vertical). Lower until upper arms parallel to floor. Press back up. Upright torso shifts emphasis to triceps.' },
  { name: 'Diamond Push-Up', muscle_group: 'Triceps', secondary_muscles: 'Chest', equipment: 'Bodyweight', instructions: 'Place hands close together forming a diamond shape. Perform push-up keeping elbows tight to body. More tricep-focused than standard push-up.' },
  { name: 'Tricep Kickback', muscle_group: 'Triceps', secondary_muscles: '', equipment: 'Dumbbell', instructions: 'Hinge forward, upper arm parallel to floor. Extend forearm back to straight. Lower with control. Best with lighter weight and strict form.' },

  // CORE
  { name: 'Plank', muscle_group: 'Core', secondary_muscles: 'Shoulders,Glutes', equipment: 'Bodyweight', instructions: 'Forearms on floor, body in straight line from head to feet. Squeeze glutes and abs. Hold for time.' },
  { name: 'Cable Crunch', muscle_group: 'Core', secondary_muscles: '', equipment: 'Cable Machine,Rope', instructions: 'Kneel facing cable, rope held at either side of head. Contract abs to crunch down toward floor. Do not pull with arms — movement must come from abs.' },
  { name: 'Hanging Leg Raise', muscle_group: 'Core', secondary_muscles: 'Hip Flexors', equipment: 'Pull-Up Bar', instructions: 'Hang from bar with arms extended. Raise legs until parallel to floor or higher. Lower slowly. Demands grip and core strength.' },
  { name: 'Ab Rollout', muscle_group: 'Core', secondary_muscles: 'Shoulders,Lats', equipment: 'Ab Wheel,Barbell', instructions: 'Kneel holding ab wheel at knees. Roll forward extending body toward floor. Roll back using core — do NOT let hips sag.' },
  { name: 'Russian Twist', muscle_group: 'Core', secondary_muscles: 'Obliques', equipment: 'Bodyweight,Weight Plate', instructions: 'Sit with knees bent, lean back 45 degrees. Rotate torso side to side touching weight to floor. Targets obliques strongly.' },
  { name: 'Pallof Press', muscle_group: 'Core', secondary_muscles: 'Shoulders', equipment: 'Cable Machine,Band', instructions: 'Stand sideways to cable. Hold handle at chest. Press straight out, resist rotation. Hold 2 seconds. Return. Anti-rotation core exercise.' },
  { name: 'Dead Bug', muscle_group: 'Core', secondary_muscles: 'Hip Flexors', equipment: 'Bodyweight', instructions: 'Lie on back, arms straight up, hips and knees at 90 degrees. Lower opposite arm and leg toward floor. Return and alternate. Keep lower back pressed to floor.' },
  { name: 'Side Plank', muscle_group: 'Core', secondary_muscles: 'Obliques,Glutes', equipment: 'Bodyweight', instructions: 'Lie on side, forearm under shoulder. Lift hips forming straight line. Hold for time. Targets obliques and lateral stability. Can be progressed with hip dips.' },

  // GLUTES
  { name: 'Hip Thrust', muscle_group: 'Glutes', secondary_muscles: 'Hamstrings,Core', equipment: 'Barbell,Bench', instructions: 'Sit with upper back on bench, barbell over hip crease. Plant feet hip-width. Drive hips up until body forms straight line from knees to shoulders. Squeeze glutes hard at top.' },
  { name: 'Glute Bridge', muscle_group: 'Glutes', secondary_muscles: 'Hamstrings,Core', equipment: 'Bodyweight,Barbell', instructions: 'Lie on back, knees bent, feet flat. Drive hips toward ceiling squeezing glutes. Hold 1-2 seconds at top. Return. Excellent warm-up or beginner glute builder.' },
  { name: 'Cable Kickback', muscle_group: 'Glutes', secondary_muscles: 'Hamstrings', equipment: 'Cable Machine,Ankle Strap', instructions: 'Attach ankle strap. Face cable, hold support. Kick leg back and slightly up. Squeeze glute at top. Return slowly.' },
  { name: 'Sumo Deadlift', muscle_group: 'Glutes', secondary_muscles: 'Hamstrings,Adductors,Back', equipment: 'Barbell', instructions: 'Wide stance with toes pointed out, hands inside legs. Lower hips more than conventional deadlift. Drive hips through to lock out. More glute and adductor involvement.' },
  { name: 'Single-Leg Glute Bridge', muscle_group: 'Glutes', secondary_muscles: 'Hamstrings,Core', equipment: 'Bodyweight', instructions: 'Lie on back, one knee bent, other leg extended. Drive hips up using one leg. Higher demand on glute and hamstring of working leg.' },

  // FULL BODY
  { name: 'Barbell Clean', muscle_group: 'Full Body', secondary_muscles: 'Traps,Core,Legs,Shoulders', equipment: 'Barbell', instructions: 'Start over mid-foot. First pull: bar to knees. Second pull: explosive triple extension of ankles, knees, hips. Drop under bar catching on front delts. Technical Olympic lift.' },
  { name: "Farmer's Walk", muscle_group: 'Full Body', secondary_muscles: 'Core,Traps,Grip,Legs', equipment: 'Dumbbells,Kettlebells', instructions: 'Pick up heavy implements with neutral grip. Walk upright for distance or time. Builds grip, traps, core stability, and conditioning simultaneously.' },
  { name: 'Kettlebell Swing', muscle_group: 'Full Body', secondary_muscles: 'Glutes,Hamstrings,Core,Shoulders', equipment: 'Kettlebell', instructions: 'Hinge at hips with kettlebell between legs. Drive hips explosively forward projecting bell to shoulder height. Hinge back absorbing force. Hip hinge is the key movement pattern.' },
  { name: 'Box Jump', muscle_group: 'Full Body', secondary_muscles: 'Calves,Core', equipment: 'Box', instructions: 'Stand in front of box. Dip into quarter squat, swing arms, jump onto box landing softly with bent knees. Step down. Builds explosive power.' },
  { name: 'Thruster', muscle_group: 'Full Body', secondary_muscles: 'Shoulders,Core,Triceps', equipment: 'Barbell,Dumbbells,Kettlebells', instructions: 'Hold weight at shoulder height. Squat down, then as you rise drive the weight overhead in one continuous movement. A front squat into a push press.' },
  { name: 'Power Clean', muscle_group: 'Full Body', secondary_muscles: 'Traps,Core,Legs', equipment: 'Barbell', instructions: 'Similar to clean but caught in a partial squat rather than full squat. Explosive pulling movement targeting posterior chain and power development.' },

  // CHEST — gym-specific additions
  { name: 'Landmine Press', muscle_group: 'Chest', secondary_muscles: 'Front Deltoid,Triceps', equipment: 'Barbell,Landmine', instructions: 'Load one end of barbell in landmine attachment. Press bar up and slightly forward from chest height using one or both hands. More shoulder-friendly angle than flat press.' },
  { name: 'Single-Arm Landmine Press', muscle_group: 'Chest', secondary_muscles: 'Front Deltoid,Triceps,Core', equipment: 'Barbell,Landmine', instructions: 'Kneel or stand. Hold end of landmine bar with one hand at shoulder height. Press diagonally upward to full arm extension. Demands unilateral core stability.' },
  { name: 'Dumbbell Squeeze Press', muscle_group: 'Chest', secondary_muscles: 'Triceps', equipment: 'Dumbbells,Bench', instructions: 'Lie on bench holding dumbbells pressed together above chest, palms facing each other. Lower both together keeping constant squeeze between them. Press back up. High pec activation.' },
  { name: 'Band Push-Up', muscle_group: 'Chest', secondary_muscles: 'Triceps,Core,Front Deltoid', equipment: 'Elastieken', instructions: 'Loop resistance band across upper back, hold ends under palms. Perform push-ups with added band resistance. Band increases load at lockout, rewarding full extension.' },
  { name: 'Incline Dumbbell Flyes', muscle_group: 'Chest', secondary_muscles: 'Front Deltoid', equipment: 'Dumbbells,Bench', instructions: 'Set bench to 30-45 degrees. Hold dumbbells above upper chest with slight elbow bend. Open arms in wide arc feeling a stretch across upper chest. Reverse the arc to return.' },

  // BACK — gym-specific additions
  { name: 'Landmine Row', muscle_group: 'Back', secondary_muscles: 'Biceps,Rear Deltoid', equipment: 'Barbell,Landmine', instructions: 'Stand over barbell in landmine attachment, hinge forward. Row bar to hip in single-arm or both hands. Allows natural wrist rotation for a comfortable rowing position.' },
  { name: 'Meadows Row', muscle_group: 'Back', secondary_muscles: 'Biceps,Rear Deltoid', equipment: 'Barbell,Landmine', instructions: 'Stand perpendicular to landmine, stagger feet. With outside hand grab end of bar. Row aggressively toward hip, lead with elbow. Excellent for lat thickness.' },
  { name: 'Lat Pulldown (V-handle)', muscle_group: 'Back', secondary_muscles: 'Biceps,Rear Deltoid', equipment: 'Pulley,V-handle', instructions: 'Attach V-handle to overhead pulley. Pull down toward upper chest with a neutral grip. Elbows drive down and back. Neutral grip often allows heavier load and less shoulder stress.' },
  { name: 'Straight-Arm Pulldown', muscle_group: 'Back', secondary_muscles: 'Core,Triceps', equipment: 'Pulley,Straight Bar', instructions: 'Stand facing overhead pulley with straight bar. Keep arms nearly straight throughout. Pull bar from eye level down to thighs in an arc. Isolates lat without bicep involvement.' },
  { name: 'Rope Pullover', muscle_group: 'Back', secondary_muscles: 'Core,Triceps', equipment: 'Pulley,Rope', instructions: 'Kneel facing overhead pulley with rope attachment. With arms extended, pull rope from overhead to hips in an arc. Keep elbows soft. Excellent lat stretch and contraction.' },
  { name: 'Seated Row (D-handle)', muscle_group: 'Back', secondary_muscles: 'Biceps,Rear Deltoid', equipment: 'Pulley,D-handles', instructions: 'Attach D-handles to low pulley. Sit with slight forward lean. Row both handles to lower ribcage with neutral grip. Drive elbows back, squeeze shoulder blades together. Return slowly.' },
  { name: 'Single-Arm Cable Row', muscle_group: 'Back', secondary_muscles: 'Biceps,Rear Deltoid,Core', equipment: 'Pulley,D-handles', instructions: 'Attach D-handle to low pulley. Sit or stand facing cable. Row single arm to hip driving elbow back. Anti-rotation demand increases core challenge.' },
  { name: 'Band Pull-Apart', muscle_group: 'Back', secondary_muscles: 'Rear Deltoid,Rotator Cuff', equipment: 'Elastieken', instructions: 'Hold resistance band at shoulder width with straight arms in front. Pull band apart until it touches your chest, squeezing shoulder blades together. Control return. Excellent shoulder health exercise.' },
  { name: 'RowErg (Rowing Machine)', muscle_group: 'Back', secondary_muscles: 'Legs,Core,Biceps,Glutes', equipment: 'RowErg', instructions: 'Set erg damper to 4-6. Drive with legs first, then lean back, then pull handle to lower sternum in one fluid sequence. Return by extending arms, leaning forward, then bending knees. Powerful conditioning tool.' },
  { name: 'Good Morning', muscle_group: 'Back', secondary_muscles: 'Hamstrings,Glutes', equipment: 'Barbell', instructions: 'Bar on upper traps. Hinge at hips with slight knee bend, lowering torso toward horizontal. Keep back flat throughout. Drive hips through to return. Excellent posterior chain builder.' },

  // SHOULDERS — gym-specific additions
  { name: 'Landmine Press (Shoulder)', muscle_group: 'Shoulders', secondary_muscles: 'Triceps,Upper Chest', equipment: 'Barbell,Landmine', instructions: 'Hold end of landmine bar at shoulder height with one hand. Press diagonally upward to full arm extension. Arc of motion is more shoulder-friendly than strict overhead press.' },
  { name: 'Cable Face Pull (Rope)', muscle_group: 'Shoulders', secondary_muscles: 'Rear Deltoid,Traps,Rotator Cuff', equipment: 'Pulley,Rope', instructions: 'Set pulley at face height with rope attachment. Pull rope to forehead, elbows flared high and wide. Externally rotate at end. Non-negotiable for shoulder health.' },
  { name: 'Cable Lateral Raise (D-handle)', muscle_group: 'Shoulders', secondary_muscles: 'Traps', equipment: 'Pulley,D-handles', instructions: 'Stand sideways to low pulley. Grab D-handle with far hand. Raise arm to shoulder height in a lateral arc. Cable provides constant tension unlike dumbbells.' },
  { name: 'Dumbbell Lateral Raise (seated)', muscle_group: 'Shoulders', secondary_muscles: 'Traps', equipment: 'Dumbbells,Bench', instructions: 'Sit on end of bench, dumbbells at sides. Raise arms to shoulder height keeping slight elbow bend. Seated version reduces body swing for stricter isolation.' },
  { name: 'Band Lateral Raise', muscle_group: 'Shoulders', secondary_muscles: 'Traps', equipment: 'Elastieken', instructions: 'Stand on resistance band holding ends. Raise arms to the side to shoulder height. Bands load progressively through range of motion. Good for high-rep shoulder work.' },
  { name: 'Plate Front Raise', muscle_group: 'Shoulders', secondary_muscles: 'Chest', equipment: 'Plates', instructions: 'Hold weight plate at 3 and 9 o\'clock. Raise straight out in front to shoulder height. Lower slowly. The disc grip challenges forearms and wrists additionally.' },
  { name: 'Kettlebell Press', muscle_group: 'Shoulders', secondary_muscles: 'Triceps,Core', equipment: 'Kettlebell', instructions: 'Clean kettlebell to rack position (resting on forearm, bell behind hand). Press overhead to full extension. Lower with control. The offset weight demands greater stability.' },

  // LEGS — gym-specific additions
  { name: 'Barbell Pause Squat', muscle_group: 'Legs', secondary_muscles: 'Glutes,Core', equipment: 'Barbell,Squat Rack', instructions: 'Perform back squat but pause 2-3 seconds at parallel before driving up. Eliminates stretch reflex, building pure strength out of the hole. Excellent for technique.' },
  { name: 'Landmine Squat', muscle_group: 'Legs', secondary_muscles: 'Glutes,Core', equipment: 'Barbell,Landmine', instructions: 'Hold end of landmine bar at chest with both hands. Squat down, keeping torso upright due to the diagonal load. Easier on lower back than barbell back squat.' },
  { name: 'Dumbbell Romanian Deadlift', muscle_group: 'Legs', secondary_muscles: 'Glutes,Lower Back', equipment: 'Dumbbells', instructions: 'Stand holding dumbbells in front of thighs. Push hips back lowering dumbbells along legs until hamstring stretch is felt. Drive hips through to return. Keep back flat throughout.' },
  { name: 'Kettlebell Romanian Deadlift', muscle_group: 'Legs', secondary_muscles: 'Glutes,Lower Back', equipment: 'Kettlebell', instructions: 'Hold kettlebell(s) in front. Push hips back lowering weight toward floor, keeping back flat. Drive hips forward to return. Kettlebell position often allows more natural movement.' },
  { name: 'Single-Leg Romanian Deadlift', muscle_group: 'Legs', secondary_muscles: 'Glutes,Core', equipment: 'Dumbbell,Kettlebell', instructions: 'Stand on one leg holding weight. Hinge at hip extending free leg behind for counterbalance. Lower weight toward floor, keep back flat. Return to upright. Demands balance and hip stability.' },
  { name: 'Barbell Hip Thrust', muscle_group: 'Legs', secondary_muscles: 'Hamstrings,Core', equipment: 'Barbell,Bench', instructions: 'Upper back on bench, barbell over hip crease. Feet hip-width flat on floor. Drive hips upward until fully extended. Squeeze glutes hard at top. Primarily a glute exercise but places high demand on hamstrings.' },
  { name: 'Box Step-Up (Weighted)', muscle_group: 'Legs', secondary_muscles: 'Glutes,Core', equipment: 'Box,Dumbbells,Barbell', instructions: 'Hold dumbbells or barbell. Place one foot on box, drive up to standing. Lower under control. Trains unilateral leg strength and hip extension. Drive through the heel of the elevated foot.' },
  { name: 'Cossack Squat', muscle_group: 'Legs', secondary_muscles: 'Adductors,Core', equipment: 'Bodyweight,Dumbbell,Kettlebell', instructions: 'Wide stance. Shift weight to one side lowering into a deep lateral lunge. Other leg remains straight with heel on floor. Return to centre. Develops hip mobility and adductor strength.' },
  { name: 'Nordic Hamstring Curl', muscle_group: 'Legs', secondary_muscles: 'Calves,Glutes', equipment: 'Bench', instructions: 'Kneel with feet anchored (under bench or held). Slowly lower body toward floor resisting with hamstrings. Push up with hands. One of the most effective hamstring exercises for injury prevention.' },
  { name: 'Standing Hip Abduction (Band)', muscle_group: 'Legs', secondary_muscles: 'Glutes', equipment: 'Crab-Walk Elastieken', instructions: 'Place band around ankles. Stand with slight knee bend. Raise one leg out to the side against band resistance. Control the return. Targets gluteus medius.' },
  { name: 'Crab Walk', muscle_group: 'Legs', secondary_muscles: 'Glutes,Core', equipment: 'Crab-Walk Elastieken', instructions: 'Place band around ankles or just above knees. Assume quarter squat position. Step sideways maintaining tension in band and consistent squat depth. Switch directions. Activates glute medius.' },
  { name: 'Lateral Band Walk (Above Knees)', muscle_group: 'Legs', secondary_muscles: 'Glutes', equipment: 'Crab-Walk Elastieken', instructions: 'Band just above knees. Stand with feet hip-width, slight squat. Step sideways with control, maintaining band tension. Keep feet parallel, do not let knees cave in.' },
  { name: 'Sissy Squat', muscle_group: 'Legs', secondary_muscles: '', equipment: 'Bodyweight', instructions: 'Stand holding light support. Rise onto toes and lean body back while bending knees, lowering body toward floor with shins angled back. Return by driving hips forward. Extreme quad isolation.' },
  { name: 'Wall Sit', muscle_group: 'Legs', secondary_muscles: '', equipment: 'Bodyweight', instructions: 'Back flat against wall. Lower into seated position at 90-degree knee angle. Hold for time. Isometric quad strength builder. Can add dumbbells on thighs to increase difficulty.' },
  { name: 'Landmine Romanian Deadlift', muscle_group: 'Legs', secondary_muscles: 'Glutes,Lower Back', equipment: 'Barbell,Landmine', instructions: 'Hold end of landmine bar with one or both hands. Hinge at hips lowering the bar as your hips go back. Keep back flat. Drive hips forward to return. The angled load is easy on the lower back.' },
  { name: 'Step-Up to Reverse Lunge', muscle_group: 'Legs', secondary_muscles: 'Glutes,Core', equipment: 'Box,Dumbbells', instructions: 'Step onto box, drive to standing. Step back off into a reverse lunge before switching. Combines step-up strength with lunge hip control in one fluid movement.' },
  { name: 'SkiErg', muscle_group: 'Legs', secondary_muscles: 'Core,Shoulders,Back', equipment: 'SkiErg', instructions: 'Stand facing SkiErg. Pull handles down simultaneously in a powerful skiing motion driving hips back and knees slightly bent. Stand back up as handles return. Can also be done alternating. Excellent conditioning.' },

  // BICEPS — gym-specific additions
  { name: 'EZ-Bar Curl', muscle_group: 'Biceps', secondary_muscles: 'Forearms', equipment: 'EZ-Bar', instructions: 'Hold EZ-bar with underhand grip on angled portion. Curl to shoulder height keeping elbows at sides. The angled grip reduces wrist strain compared to straight barbell.' },
  { name: 'EZ-Bar Preacher Curl', muscle_group: 'Biceps', secondary_muscles: 'Forearms', equipment: 'EZ-Bar,Bench', instructions: 'Rest upper arms on incline bench pad. Curl EZ-bar from full extension to peak contraction. Eliminates body swing for strict isolation. Full extension at bottom is essential.' },
  { name: 'Cable Curl (Rope)', muscle_group: 'Biceps', secondary_muscles: 'Forearms,Brachialis', equipment: 'Pulley,Rope', instructions: 'Attach rope to low pulley. Curl rope to chin allowing wrists to supinate at the top. Rope allows natural wrist rotation increasing peak contraction.' },
  { name: 'Pulley Curl (D-handle)', muscle_group: 'Biceps', secondary_muscles: 'Forearms', equipment: 'Pulley,D-handles', instructions: 'Attach D-handle to low pulley. Curl single arm to shoulder height, elbow stays stationary. Constant cable tension throughout range of motion.' },
  { name: 'Kettlebell Curl', muscle_group: 'Biceps', secondary_muscles: 'Forearms,Brachialis', equipment: 'Kettlebell', instructions: 'Hold kettlebell with hand through handle, bell hanging below. Curl to shoulder height. The offset weight challenges grip and forearm stability throughout the movement.' },
  { name: 'Band Curl', muscle_group: 'Biceps', secondary_muscles: 'Forearms', equipment: 'Elastieken', instructions: 'Stand on resistance band. Curl ends up to shoulder height. Band loads most at peak contraction. Good for finishing sets or high-rep work.' },
  { name: 'Reverse Curl', muscle_group: 'Biceps', secondary_muscles: 'Brachialis,Forearms', equipment: 'Barbell,EZ-Bar,Dumbbells', instructions: 'Hold bar with overhand (pronated) grip. Curl to shoulder height. Reverse grip shifts emphasis to brachialis and brachioradialis for complete arm development.' },
  { name: 'Cross-Body Hammer Curl', muscle_group: 'Biceps', secondary_muscles: 'Brachialis,Forearms', equipment: 'Dumbbells', instructions: 'Perform hammer curl but curl dumbbell across body toward opposite shoulder instead of straight up. Emphasizes brachialis differently than standard hammer curl.' },

  // TRICEPS — gym-specific additions
  { name: 'Tricep Pushdown (Straight Bar)', muscle_group: 'Triceps', secondary_muscles: '', equipment: 'Pulley,Straight Bar', instructions: 'Stand at high pulley with straight bar attachment. Overhand grip at shoulder-width. Push bar down to thighs keeping elbows tucked at sides. Control the return.' },
  { name: 'Tricep Pushdown (Rope)', muscle_group: 'Triceps', secondary_muscles: '', equipment: 'Pulley,Rope', instructions: 'Stand at overhead pulley with rope attachment. Push rope down, spreading rope apart at the bottom to fully extend and isolate all three heads of the tricep. Return slowly.' },
  { name: 'Overhead Cable Tricep Extension', muscle_group: 'Triceps', secondary_muscles: '', equipment: 'Pulley,Rope', instructions: 'Face away from overhead pulley holding rope behind head. Extend arms forward and down. The overhead position maximally stretches the long head of the tricep. Control the return.' },
  { name: 'EZ-Bar Skull Crusher', muscle_group: 'Triceps', secondary_muscles: '', equipment: 'EZ-Bar,Bench', instructions: 'Lie on bench, EZ-bar above chest, angled grip. Lower bar toward forehead bending at elbows. Press back to full extension. Easier on wrists than straight bar.' },
  { name: 'EZ-Bar Overhead Tricep Extension', muscle_group: 'Triceps', secondary_muscles: '', equipment: 'EZ-Bar', instructions: 'Hold EZ-bar overhead with narrow angled grip. Lower behind head by bending elbows. Press back to full extension. Overhead position provides maximum stretch of long head.' },
  { name: 'Single-Arm Cable Kickback', muscle_group: 'Triceps', secondary_muscles: '', equipment: 'Pulley,D-handles', instructions: 'Attach D-handle to low pulley. Hinge forward, upper arm parallel to floor. Extend forearm back against cable resistance. Great isolation with constant tension.' },
  { name: 'Dumbbell Tate Press', muscle_group: 'Triceps', secondary_muscles: '', equipment: 'Dumbbells,Bench', instructions: 'Lie on bench with dumbbells above chest, elbows pointed out. Lower dumbbells by bending elbows outward until they touch chest. Press back up by extending elbows. Targets medial head of tricep.' },
  { name: 'Band Tricep Pushdown', muscle_group: 'Triceps', secondary_muscles: '', equipment: 'Elastieken', instructions: 'Anchor band at head height. Grip band and push down to full extension, keeping elbows at sides. Good for activation warm-up or high-rep finisher sets.' },
  { name: 'Landmine Tricep Extension', muscle_group: 'Triceps', secondary_muscles: 'Core', equipment: 'Barbell,Landmine', instructions: 'Kneel in front of landmine attachment. Hold end of bar overhead. Bend elbows lowering bar behind head. Press back to full extension. The angled load is wrist-friendly.' },

  // CORE — gym-specific additions
  { name: 'Landmine Rotation', muscle_group: 'Core', secondary_muscles: 'Shoulders,Obliques', equipment: 'Barbell,Landmine', instructions: 'Stand perpendicular to landmine. Clasp hands at end of bar with arms straight. Rotate the bar from one side to the other through a wide arc. Keep core braced throughout. Power from rotation, not arms.' },
  { name: 'Pallof Press (Band)', muscle_group: 'Core', secondary_muscles: 'Shoulders', equipment: 'Elastieken', instructions: 'Anchor band at chest height to a fixed point. Stand sideways, hold band at chest. Press straight out and hold 2 seconds. Return. Resist the rotational pull. Anti-rotation stability exercise.' },
  { name: 'Cable Woodchop (High to Low)', muscle_group: 'Core', secondary_muscles: 'Shoulders,Obliques', equipment: 'Pulley,D-handles', instructions: 'Set pulley high. Stand sideways, grip D-handle with both hands. Pull handle diagonally down and across body as if chopping wood. Rotate through thoracic spine. Control return.' },
  { name: 'Cable Woodchop (Low to High)', muscle_group: 'Core', secondary_muscles: 'Shoulders,Obliques', equipment: 'Pulley,D-handles', instructions: 'Set pulley low. Stand sideways, grip D-handle with both hands. Pull handle diagonally upward and across body. Rotate through thoracic spine. The reverse pattern of the high-to-low chop.' },
  { name: 'Hollow Hold', muscle_group: 'Core', secondary_muscles: 'Hip Flexors', equipment: 'Bodyweight', instructions: 'Lie on back. Raise legs to 45 degrees and shoulders off floor with arms reaching overhead. Lower back pressed into floor. Hold for time. Foundation of gymnastics core strength.' },
  { name: 'L-Sit (Bench)', muscle_group: 'Core', secondary_muscles: 'Hip Flexors,Triceps', equipment: 'Bench', instructions: 'Sit on edge of bench, hands beside hips. Press into bench lifting hips and extending legs straight out. Hold position. Demands tremendous core and hip flexor strength.' },
  { name: 'Suitcase Carry', muscle_group: 'Core', secondary_muscles: 'Traps,Grip,Obliques', equipment: 'Dumbbell,Kettlebell', instructions: 'Hold a single dumbbell or kettlebell at one side. Walk upright, resisting lateral lean. Forces core to work anti-laterally. Builds obliques and quadratus lumborum.' },
  { name: 'Hanging Knee Raise', muscle_group: 'Core', secondary_muscles: 'Hip Flexors', equipment: 'Pulley', instructions: 'Attach cuffs to overhead cable. Hang with cuffs on wrists or hold bar. Raise knees toward chest contracting abs. Lower slowly. Beginner progression before straight-leg raise.' },
  { name: 'Cable Crunch (Rope)', muscle_group: 'Core', secondary_muscles: '', equipment: 'Pulley,Rope', instructions: 'Kneel facing overhead pulley with rope attachment. Hold rope at sides of head. Contract abs crunching down toward floor — movement comes from abs, not arms. Hold 1 second at bottom.' },
  { name: 'Waterbag Carry', muscle_group: 'Core', secondary_muscles: 'Shoulders,Traps,Legs', equipment: 'Waterzak', instructions: 'Hug or hold waterbag at chest or overhead. Walk, lunge, or squat. The unpredictable shifting water forces constant core stabilisation in all planes. Functional strength builder.' },
  { name: 'Waterbag Slam', muscle_group: 'Core', secondary_muscles: 'Shoulders,Back,Legs', equipment: 'Waterzak', instructions: 'Hold waterbag overhead with both hands. Slam it down powerfully toward floor engaging the entire posterior and anterior chain. Pick up and repeat. Excellent power and conditioning exercise.' },
  { name: 'Plate Rotation', muscle_group: 'Core', secondary_muscles: 'Obliques,Shoulders', equipment: 'Plates', instructions: 'Stand holding a weight plate with both hands. Rotate the plate in a large horizontal circle in front of the body. Alternate direction each set. Challenges rotational core strength and shoulder stability.' },

  // GLUTES — gym-specific additions
  { name: 'Cable Kickback (Ankle Cuff)', muscle_group: 'Glutes', secondary_muscles: 'Hamstrings', equipment: 'Pulley,Kickback Straps', instructions: 'Attach kickback strap to ankle. Face low pulley, hold support. Kick leg back and slightly up squeezing glute at top. Keep hips square. Return slowly. Excellent glute isolation.' },
  { name: 'Cable Pull-Through', muscle_group: 'Glutes', secondary_muscles: 'Hamstrings,Lower Back', equipment: 'Pulley,Rope', instructions: 'Stand facing away from low pulley. Reach between legs grabbing rope. Hinge forward letting rope pull between legs. Drive hips through to stand, squeezing glutes. Hip hinge pattern similar to kettlebell swing.' },
  { name: 'Banded Hip Thrust', muscle_group: 'Glutes', secondary_muscles: 'Hamstrings,Core', equipment: 'Elastieken,Bench', instructions: 'Set up for hip thrust with resistance band placed just above knees. Push knees out against band as you thrust hips up. Band increases glute medius activation alongside the main glute max.' },
  { name: 'Banded Glute Bridge', muscle_group: 'Glutes', secondary_muscles: 'Hamstrings,Core', equipment: 'Elastieken', instructions: 'Lie on back with band just above knees. Drive knees apart against band as you bridge up. Adds lateral glute activation to standard bridge.' },
  { name: 'Landmine Romanian Deadlift (Glutes)', muscle_group: 'Glutes', secondary_muscles: 'Hamstrings,Lower Back', equipment: 'Barbell,Landmine', instructions: 'Hold end of landmine bar with both hands. Push hips back lowering bar as you hinge. Feel stretch through glutes and hamstrings. Drive hips forward to return. Angled load is lower back friendly.' },
  { name: 'Kettlebell Deadlift', muscle_group: 'Glutes', secondary_muscles: 'Hamstrings,Lower Back,Core', equipment: 'Kettlebell', instructions: 'Stand with kettlebell between feet. Hinge at hips keeping back flat, grip handle. Drive through floor to stand extending hips fully. Lower under control. Great deadlift teaching tool.' },
  { name: 'Monster Walk', muscle_group: 'Glutes', secondary_muscles: 'Legs', equipment: 'Crab-Walk Elastieken', instructions: 'Place band above or below knees. Take diagonal steps forward — step out and forward alternating sides in a monster-walk pattern. Keep tension in band throughout. Targets glute medius and hip abductors.' },
  { name: 'Donkey Kick (Cable)', muscle_group: 'Glutes', secondary_muscles: 'Hamstrings', equipment: 'Pulley,Kickback Straps', instructions: 'Attach kickback strap to ankle. On hands and knees or standing bent over. Drive knee forward then kick foot back and up. Keep hips square. Targets glute max through full extension.' },
  { name: 'Standing Abduction (Cable)', muscle_group: 'Glutes', secondary_muscles: '', equipment: 'Pulley,Cuffs', instructions: 'Attach cuff to ankle. Stand sideways to low pulley. Lift attached leg out to the side against cable resistance. Control return. Isolates gluteus medius.' },

  // FULL BODY — gym-specific additions
  { name: 'Kettlebell Turkish Get-Up', muscle_group: 'Full Body', secondary_muscles: 'Core,Shoulders,Glutes,Legs', equipment: 'Kettlebell', instructions: 'Lie holding kettlebell straight up with one arm. Roll to elbow, then hand, sweep leg through, lunge up to standing. Reverse to return. The gold standard of full-body stability and mobility.' },
  { name: 'Landmine Clean and Press', muscle_group: 'Full Body', secondary_muscles: 'Legs,Core,Shoulders,Back', equipment: 'Barbell,Landmine', instructions: 'Row end of landmine bar to shoulder in a clean motion. Immediately press overhead. Lower and repeat. Combines a pulling and pressing movement in one fluid sequence.' },
  { name: 'Kettlebell Clean and Press', muscle_group: 'Full Body', secondary_muscles: 'Core,Legs,Shoulders', equipment: 'Kettlebell', instructions: 'Clean kettlebell from swing to rack position at shoulder. Immediately press overhead. Lower back through rack to swing. Technical movement combining hip drive with overhead press.' },
  { name: 'Sandbag / Waterbag Complex', muscle_group: 'Full Body', secondary_muscles: 'Core,Shoulders,Legs,Back', equipment: 'Waterzak', instructions: 'Perform a series of movements with the waterbag: deadlift, clean to shoulder, squat, press, rotation. Flow between movements with minimal rest. Builds grip, conditioning, and total body strength.' },
  { name: 'SkiErg Sprint', muscle_group: 'Full Body', secondary_muscles: 'Core,Shoulders,Back,Legs', equipment: 'SkiErg', instructions: 'Pull SkiErg handles down explosively in powerful double-arm pull, hinging at hips and bending knees. Reset quickly and repeat at maximum effort. Used for short sprints (10-30 seconds) or longer conditioning intervals.' },
  { name: 'Waterbag Squat and Press', muscle_group: 'Full Body', secondary_muscles: 'Legs,Shoulders,Core', equipment: 'Waterzak', instructions: 'Hold waterbag at chest or shoulder. Squat down, then as you rise press the bag overhead. The shifting water creates instability demanding constant adjustment. Excellent functional strength exercise.' },
  { name: 'Dumbbell Complex', muscle_group: 'Full Body', secondary_muscles: 'Core,Legs,Shoulders,Back', equipment: 'Dumbbells', instructions: 'Perform a series of exercises back-to-back without putting dumbbells down: Romanian deadlift, hang clean, front squat, press. Each rep flows into the next. Builds strength and serious conditioning.' },
  { name: 'Barbell Complex', muscle_group: 'Full Body', secondary_muscles: 'Core,Legs,Shoulders,Back', equipment: 'Barbell', instructions: 'Perform 6 reps each without setting bar down: Romanian deadlift, bent-over row, hang power clean, front squat, press. Classic barbell complex for conditioning and strength endurance.' }
]

const existing = db.prepare('SELECT COUNT(*) as count FROM exercises WHERE is_custom = 0').get()
if (existing.count > 0) {
  console.log(`Database already has ${existing.count} exercises. Skipping seed.`)
  console.log('Delete ptapp.db to re-seed.')
  process.exit(0)
}

const insert = db.prepare(`
  INSERT INTO exercises (name, muscle_group, secondary_muscles, equipment, instructions, is_custom, trainer_id)
  VALUES (?, ?, ?, ?, ?, 0, NULL)
`)

const insertMany = db.transaction((exercises) => {
  for (const ex of exercises) {
    insert.run(ex.name, ex.muscle_group, ex.secondary_muscles || null, ex.equipment || null, ex.instructions || null)
  }
})

insertMany(EXERCISES)
console.log(`Seeded ${EXERCISES.length} exercises successfully.`)
